### ISSUE TITLE
Track progress for Kubernetes 1.8 / kubernetes-kafka v3.0.0

### ISSUE THREAD

**Issue by solsson** [Yolean/kubernetes-kafka#84]
Manifests:

- [x] Update to 1.8 workload API versions
  - 8e2de05
  - 03ddbf1
- [x] Storage `Retain` (#85)
- [ ] Retain for minikube too

Test open PRs:

- [x] Zookeeper liveness (#76, d0a5088)
- [x] metrics-improve-scrape-times (f89bd74)
  - [ ] test with https://github.com/Yolean/kubernetes-monitoring/pull/4
- [ ] #77 remove overrides (any votes there?)
   - if not the whole PR, maybe ed9fe4e as fix for #72?
- [x] kafka-manager #83 + 03ddbf1
- [x] kubernetes events to kafka (#60) [1.8-kube-events](https://github.com/Yolean/kubernetes-kafka/compare/1.8-kube-events)

Test tests:

- [ ] kafkacat based, delete brokers etc 
- [ ] java based, delete brokers etc

Structure:

- [ ] Addons -> master, selected using kubectl apply [folder]
   - See "1.8-" branches like 1.8-logs-streaming
   - See label [v3.1](https://github.com/Yolean/kubernetes-kafka/pulls?q=is%3Apr+is%3Aopen+label%3Amerge1.8)

**Comment by solsson** [comment]
[ ] rename manifests from NNname.yml to NN-name.yml?

**Comment by solsson** [comment]
Found an explanation for why `selector:` needs to be added to workload API manifests: 
From [daemonset](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) but I guess it applies to other resources as well:
"The pod selector will no longer be defaulted when left empty. Selector defaulting was not compatible with kubectl apply."

**Comment by solsson** [comment]
An update on testing, based on https://github.com/Yolean/kubernetes-kafka/pull/79#issuecomment-336825949. I lack the Kafka experiment to interpret current results, so I think I want 3 tests that do essentially the same but with different clients.

What we want to assert is basically "uptime" in the face of re-scheduled broker and zk pods, caused by things like node downtime, cluster upgrades or zone outages. Tests continuously "bootstrap" + consume from a topic with 2 replicas (b8bfda8) + regularly produce messages + assert that those messages get consumed.

Measurements of throughput etc will have to wait until we have Prometheus monitoring up and running (#49 + [Yolean/kubernetes-monitoring](https://github.com/Yolean/kubernetes-monitoring) + [ServiceMonitor](https://coreos.com/operators/prometheus/docs/latest/user-guides/cluster-monitoring.html#setup-monitoring)s + [rules](https://coreos.com/operators/prometheus/docs/latest/user-guides/alerting.html)).

The three tests are:
 * The kafka image's console producer + consumer (test-produce-consume)
 * Kafkacat (#79)
 * https://github.com/Yolean/kafka-test-failover (i.e. the java client with some typical usage pattern/config)

As a complement it'll be interesting to have kafkacat with new bootstrap for every assert run, i.e. https://github.com/Yolean/kubernetes-kafka/blob/master/test/basic-with-kafkacat.yml prior to #79)

**Comment by solsson** [comment]
My new favorite oneliner (with alias from https://github.com/solsson/kubectx/pull/1#issuecomment-340931151):
```bash
k get pods --all-namespaces -w | sed "s/^/$(date +%F%T) /"
```
:)

**Comment by solsson** [comment]
Killing pods and watching [test readiness](https://github.com/Yolean/kube-test) I tend to need a tab that does a human readable variant of #60. My new favorite oneliner 😄  (with alias from https://github.com/solsson/kubectx/pull/1#issuecomment-340931151):
```bash
while :; do k get pods --all-namespaces -w; done | awk '{ print strftime("%FT%T"), $0 }'
```

**Comment by solsson** [comment]
Tests have been put into practice in https://github.com/Yolean/kubernetes-kafka/pull/79#issuecomment-342074301

Huge improvement that we don't spin up 2 JVMs every 10s :)

**Comment by solsson** [comment]
Closing this messy ticket in favor of https://github.com/Yolean/kubernetes-kafka/milestone/1, with scope reductions -> https://github.com/Yolean/kubernetes-kafka/milestone/2.
